### ISSUE TITLE
Map:_getTileQuad() doesn't respect the tileset.margin value

### ISSUE THREAD

**Issue by zombrodo** [tesselode/cartographer#5]
When using a tileset that has a `margin` (as opposed to `spacing`), the function that creates the quads doesn't make use of it when extracting quads. This results in the following:

![image](https://user-images.githubusercontent.com/7221020/97101029-a6bf6f00-16fe-11eb-8279-583f17a277b7.png)

Here's the call to `love.graphics.newQuad` that misses the margin: 
https://github.com/tesselode/cartographer/blob/master/cartographer.lua#L793-L797

The quick solution I added locally was to add the `margin` to the result of `<x|y> * (tileset.<width|height> + tileset.spacing)`, so it becomes:

```lua
tileset.margin + (x * (tileset.tilewidth + tileset.spacing))
tileset.margin + (y * (tileset.tileheight + tileset.spacing))
```

This'll end up with the correct result:

![image](https://user-images.githubusercontent.com/7221020/97101080-1f263000-16ff-11eb-980a-cf65c49e7eca.png)

I'm pretty sure that it's _close_ to the right answer, but is probably wrong - the `margin` is also ignored when converting `indexToCoordinates` (and not sure where else), and it'd probably fail that call if the `margin` was sufficiently big enough?

At that point, thought I'd leave it with you - if you want, I'm happy to go all out and fix it, but since you're familiar with the code, could be a quick fix on your end :)

**Comment by tesselode** [comment]
I don't think `indexToCoordinates` is relevant here - as long as the quads take the margin into account, everything should work fine.

Can you open a PR and I'll check and make sure everything works OK?
